// Artigos de raça de cachorro (src/content/blog/caes/<slug>.mdx) -> nome curto
// exibido nos atalhos da home. Ao publicar uma raça nova, adicione aqui.
export const DOG_BREEDS: Record<string, string> = {
  "american-bully": "American Bully",
  basenji: "Basenji",
  "blue-heeler": "Blue Heeler",
  "border-collie": "Border Collie",
  "buldogue-frances": "Buldogue Francês",
  "bull-terrier": "Bull Terrier",
  "cane-corso": "Cane Corso",
  "cavalier-king-charles-spaniel": "Cavalier King",
  chihuahua: "Chihuahua",
  "chow-chow": "Chow Chow",
  "corgi-welsh": "Corgi",
  dachshund: "Dachshund",
  dalmata: "Dálmata",
  doberman: "Doberman",
  "fila-brasileiro": "Fila Brasileiro",
  "fox-paulistinha-terrier-brasileiro": "Fox Paulistinha",
  "husky-siberiano": "Husky Siberiano",
  "jack-russell-terrier": "Jack Russell",
  "lhasa-apso": "Lhasa Apso",
  "lulu-da-pomerania": "Lulu da Pomerânia",
  maltes: "Maltês",
  "pastor-alemao": "Pastor Alemão",
  "pastor-belga-groenendael": "Pastor Belga",
  "pastor-branco-suico": "Pastor Branco Suíço",
  pequines: "Pequinês",
  pinscher: "Pinscher",
  pug: "Pug",
  rottweiler: "Rottweiler",
  "schnauzer-miniatura": "Schnauzer",
  "shar-pei": "Shar Pei",
  "shiba-inu": "Shiba Inu",
  "shih-tzu": "Shih Tzu",
  "staffordshire-bull-terrier": "Staffordshire",
  yorkshire: "Yorkshire",
};
